- .circleci/config.yml
- catalog/@orb.yaml
- catalog/executors/architect.yaml
- catalog/jobs/update.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/6025
This is the first version of the [architect orb](https://circleci.com/orbs/registry/orb/giantswarm/architect-orb).
This PR setup the CircleCI config to build, publish and promote the orb, and also a basic structure with a hello world orb.
> initial version

- docs/pull_request_template.md
:wrench: Please make sure to familiarize yourself with [Development section of README.md](../README.md#Development) before releasing a PR to this repository.
:warning: If you want to **create a new release** of this orb please read [Releases section of README.md](../README.md#Releases) carefully :exclamation:
> docs: fix typos in PR template

- .circleci/config.yml
Manually fiddling, reverting some changes in CircleCI config is part of the current release process.
This PR makes necessary adjustments.
For mode details please see [Releases section of README.md](../README.md#Releases).
> Post 0.1.1 release CircleCI config fix

- README.md
Fixes https://github.com/giantswarm/giantswarm/issues/6183.
> readme: add info about setting up App Catalog repo

- .circleci/config.yml
> Post 0.1.2 release CircleCI config fix

- src/commands/push-to-docker.yaml
Towards: giantswarm/giantswarm#6557
Merged too fast, missing a parenthesis in the command.
> fix push-to-docker

- .circleci/config.yml
- CHANGELOG.md
Towards: giantswarm/giantswarm#6557
> release new version 0.2.0

- README.md
Adding a known issue.
Towards: https://github.com/giantswarm/giantswarm/issues/6692
> Added known issue

- CHANGELOG.md
- README.md
- src/commands/push-to-app-collection.yaml
- src/executors/architect.yaml
- src/jobs/push-to-app-collection.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/6847
This PR provides a new `architect/push-to-app-collection` job which generate an app cr and pushes it to the app-collection repo, in order to deploy it.
> add push-to-app-collection job

- .circleci/config.yml
- CHANGELOG.md
Towards: https://github.com/giantswarm/giantswarm/issues/6847
Release a new version of this orb: `0.3.0`
> release new version 0.3.0

- .circleci/config.yml
Towards: https://github.com/giantswarm/giantswarm/issues/6847
> revert build changes after release

- .circleci/config.yml
- CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/6947.
> release v0.4.0

- CHANGELOG.md
- src/commands/package-and-push.yaml
- src/commands/push-to-app-collection.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/6692
> Add message link to known errors if push fails

- docs/pull_request_template.md
:wrench: Please make sure to familiarize yourself with [Development section of README.md](../README.md#Development) before releasing a PR to this repository.
:warning: If you want to **create a new release** of this orb please read [Releases section of README.md](../README.md#Releases) carefully :exclamation:
> Add checklist for updating docs to PR template

- CHANGELOG.md
> release v0.4.3

- CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/7480
> release 0.4.4

- CHANGELOG.md
create a new release with https://github.com/giantswarm/architect-orb/pull/51
> release 0.4.5

- CHANGELOG.md
> release v0.5.1

- README.md
> Fix readme internal link

- src/commands/go-test.yaml
This reverts commit 3af26e3767355727537dcedb8b97315f0366e2df.
> Fix "Goimports local (#58)"

- CHANGELOG.md
:wrench: Please make sure to familiarize yourself with [Development section of README.md](../README.md#Development) before releasing a PR to this repository.
:warning: If you want to **create a new release** of this orb please read [Releases section of README.md](../README.md#Releases) carefully :exclamation:
> Release v0.5.3

- docs/pull_request_template.md
See https://github.com/giantswarm/giantswarm/pull/8745.
> docs: update PR template

- CHANGELOG.md
- src/commands/integration-test-go-test.yaml
> Fix go path problem in integration-test job

- README.md
- docs/README.md
- docs/integration_test_job.md
- src/jobs/integration-test.yaml
Adding docs for the job and I'll then create a 0.8.2 release with the bug fix.
Readme is already quite long so I created a new page in the docs dir.
> Add docs for integration-test job

- README.md
- docs/pull_request_template.md
> docs, readme: add coding guidelines section

- CHANGELOG.md
> Release 8.0.2

- docs/integration_test_job.md
Adds more detail that the tests run in a Circle VM.
> Improve integration test docs

- .circleci/config.yml
Last step from https://github.com/giantswarm/architect-orb/pull/103
> Update architect-orb to v0.8.3

- CHANGELOG.md
- src/commands/go-test.yaml
> drop unparam from golangci-lint

- CHANGELOG.md
> release v0.8.4

- CHANGELOG.md
- src/commands/helm-chart-template.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8635.
Tested in:
- https://circleci.com/gh/giantswarm/pawel-test/25
> validation failed error: wrong value for "version" in chart: got `10.0.0`, expected `3.0.1-b851f0dc5785544ec4cc2858bee85a15bc9a5af5`, consider setting `version: "[[ .Version ]]"` in your Chart.yaml
- https://circleci.com/gh/giantswarm/pawel-test/24
> validation failed error: wrong value for "appVersion" in chart: got ``, expected `10.0.0`, consider setting `appVersion: "[[ .AppVersion ]]"` in your Chart.yaml
- https://circleci.com/gh/giantswarm/pawel-test/28
> validation failed error: version in git tag must be equal to version in pkg/project/project.go: `11.0.0` != `10.0.0-dev`, this release is **broken**, create another one
> commands/helm-chart-template: do validation with architect helm template

- CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/8635
> release v0.8.5

- .circleci/config.yml
> circleci: update architect orb to v0.8.5

- CHANGELOG.md
> Release v0.8.6

- .circleci/config.yml
- CHANGELOG.md
> Update orb to 0.8.6

- CHANGELOG.md
> Release 0.8.7 version

- .circleci/config.yml
> Update architect orb to version 0.8.7

- CHANGELOG.md
- src/commands/machine-install-go.yaml
> Update Go version used in integration test to 1.14.1

- CHANGELOG.md
> release v0.8.8

- .circleci/config.yml
- README.md
> update architect orb

- README.md
> readme: update releasing part

- CHANGELOG.md
> release 0.8.9

- CHANGELOG.md
- src/commands/helm-lint.yaml
- src/jobs/push-to-app-catalog.yaml
> Helm lint when pushing to catalog

- CHANGELOG.md
> release v0.8.10

- CHANGELOG.md
- src/commands/helm-conftest.yaml
> Only check deprecations in 1.16

- CHANGELOG.md
> release v0.8.11

- CHANGELOG.md
- README.md
- src/commands/push-to-app-collection.yaml
- src/jobs/push-to-app-collection.yaml
> Wire app force upgrade

- CHANGELOG.md
> Release version v0.8.12

- .circleci/config.yml
> Update architect orb version to v0.8.12

- CHANGELOG.md
> release v0.8.13

- CHANGELOG.md
> release v0.8.14

- .circleci/config.yml
> Dogfood orb v0.8.14

- CHANGELOG.md
> Prep for new release 0.8.15

- .circleci/config.yml
> Bump the version of architect-orb that's used

- docs/job/push-to-app-catalog.md
- docs/job/push-to-app-collection.md
> docs: fix links

- docs/job/push-to-app-catalog.md
- docs/job/push-to-app-collection.md
- docs/job/push-to-docker-legacy.md
- docs/job/push-to-docker.md
Towards https://github.com/giantswarm/giantswarm/issues/10994
> docs: add notes about architect context

- CHANGELOG.md
- src/commands/integration-test-install-tools.yaml
> Install Helm when integration testing

- CHANGELOG.md
> Release v0.8.16

- CHANGELOG.md
> Release v0.8.17

- CHANGELOG.md
- src/commands/integration-test-create-cluster.yaml
> Retry creating kind cluster if fails

- CHANGELOG.md
- src/commands/package-and-push.yaml
- src/commands/push-to-app-collection.yaml
Towards https://github.com/giantswarm/giantswarm/issues/10423
> push-to-app-catalog, push-to-app-collection: fix retries

- CHANGELOG.md
> Release v0.8.18

- CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/10423
> release v0.9.0

- .circleci/config.yml
> circleci: dogfood with 0.9.0

- CHANGELOG.md
- src/commands/kat-tests-run.yaml
- src/commands/package-and-push.yaml
> Remove helm init

- CHANGELOG.md
- src/commands/go-architect-legacy.yaml
- src/executors/architect.yaml
> Pin architect binary version to v2.0.0

- .circleci/config.yml
> Update orb version as 0.10.0

- .github/workflows/zz_generated.create_release.yaml
- .github/workflows/zz_generated.create_release_pr.yaml
> Initial github working flow

- CHANGELOG.md
- src/executors/architect.yaml
> Update architect to 2.1.3

- .circleci/config.yml
> Update circleci orb with 0.10.2

- .circleci/config.yml
Followup from https://github.com/giantswarm/architect-orb/pull/174 and https://github.com/giantswarm/architect-orb/pull/173
> Update architect-orb version to v0.11.0

- CHANGELOG.md
- src/executors/architect.yaml
Towards https://github.com/giantswarm/giantswarm/issues/13424
> Update architect to v3.0.0

- .circleci/config.yml
Dogfooding, as follow up to architect-orb 0.13.0 release
> Use architect-orb 0.13.0

- CHANGELOG.md
- src/executors/architect.yaml
> Update architect to v3.0.2

- README.md
Along the lines of https://github.com/giantswarm/architect-orb/pull/187
> Add guideline to use name on steps

- CHANGELOG.md
- docs/job/run-kat-tests.md
- src/commands/kat-tests-install-tools.yaml
- src/commands/kat-tests-run.yaml
- src/jobs/run-kat-tests.yaml
> add more parameters to run-kat-tests job

- .circleci/config.yml
- CHANGELOG.md
- src/jobs/run-kat-tests.yaml
> Add resource_class parameter to run-kat-tests job

- CHANGELOG.md
- src/commands/push-to-app-collection.yaml
- src/executors/architect.yaml
- src/jobs/push-to-app-collection.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/14557
> add configmap and secret

- CHANGELOG.md
- src/commands/integration-test-install-app-platform.yaml
- src/jobs/integration-test.yaml
> Fix setting kubeconfig when running apptestctl bootstrap

- CHANGELOG.md
- src/commands/push-to-app-collection.yaml
- src/jobs/push-to-app-collection.yaml
From push-to-app-collection. There are no non-unique apps in the
collection since the release-operator.
> Remove unique parameter

- src/commands/push-to-app-collection.yaml
Among other changes ` > ` is replaced with ` | tee ` for easier
debugging.
> Refactor for fewer steps and easier debugging

- CHANGELOG.md
- src/commands/push-to-app-collection.yaml
- src/executors/architect.yaml
Towards https://github.com/giantswarm/giantswarm/issues/14603
> Set config version in App CR in push-to-app-collection

- CHANGELOG.md
- src/jobs/integration-test.yaml
> Update apptestctl to v0.6.0

- CHANGELOG.md
- src/commands/package-and-push-with-abs.yaml
- src/executors/app-build-suite.yaml
> bump app-build-suite executor image

- .circleci/config.yml
- CHANGELOG.md
- src/commands/machine-install-go.yaml
- src/executors/architect.yaml
> Update go to 1.16.1

- CHANGELOG.md
- src/commands/integration-test-install-tools.yaml
- src/jobs/integration-test.yaml
Tested in https://github.com/giantswarm/app-exporter/pull/87
> Update versions in integration-test job

- CHANGELOG.md
- src/commands/push-to-app-collection.yaml
> Support both master and main branches for app collections

- CHANGELOG.md
- docs/job/run-tests-with-abs.md
- src/executors/app-build-suite.yaml
- src/jobs/run-tests-with-abs.yaml
Trying to get this into the next release
> update app-build-suite to 0.2.2

- CHANGELOG.md
- src/executors/architect.yaml
Use architect containing the extended chart schema from https://github.com/giantswarm/architect/pull/600
> Use architect with extended chart schema

- CHANGELOG.md
- src/commands/push-to-app-collection.yaml
> Fix push to app collection clone for master branch

- CHANGELOG.md
- src/jobs/integration-test.yaml
> Use Kubernetes 1.20.2 for kind in integration-test job

- .circleci/config.yml
> Update architect-orb version to 2.8.0

- CHANGELOG.md
- src/commands/push-to-app-collection.yaml
- src/executors/architect.yaml
- src/jobs/push-to-app-collection.yaml
Towards https://github.com/giantswarm/giantswarm/issues/16948
* Tested here: https://github.com/giantswarm/management-cluster-admission/pull/49
* Passing job: https://app.circleci.com/pipelines/github/giantswarm/management-cluster-admission/139/workflows/f21cbb61-c1ea-4da3-a666-d8b89f032ac0/jobs/624
* Result manifest in a collection: https://github.com/giantswarm/pawel-collection/commit/18476d5ea664e7b4f10a9a3b13b1893a41c4bbea
> Create Argo Application CRs when pushing to App Collection

- CHANGELOG.md
- src/commands/push-to-app-collection.yaml
- src/jobs/push-to-app-collection.yaml
Towards https://github.com/giantswarm/giantswarm/issues/17320
Tested here:
* [Test PR](https://github.com/giantswarm/management-cluster-admission/pull/53)
* [Test CI run](https://app.circleci.com/pipelines/github/giantswarm/management-cluster-admission/155/workflows/8fc8bdf5-4886-4277-9efb-149577384b15/jobs/672)
* [Test collection commit](https://github.com/giantswarm/pawel-collection/commit/38ce7529a21d888feb0a2971f025e93e7e1041bd)
> Overwrite GS apps with Argo apps

- .circleci/config.yml
> update circleci to 3.2.0

- CHANGELOG.md
- src/executors/architect.yaml
> Update architect to 3.7.1

- CHANGELOG.md
- src/commands/helm-conftest.yaml
- src/commands/helm-lint.yaml
Without a name, these step looks like this in CI:
> Add friendly name to several steps

- CHANGELOG.md
- src/executors/architect.yaml
> Update architect to v4.0.0

- CHANGELOG.md
- src/commands/push-to-app-collection.yaml
Towards https://github.com/giantswarm/giantswarm/issues/17321
> Remove pushing to helm path

- CHANGELOG.md
- src/executors/architect.yaml
Towards enabling cascading deletion with new finalizer in argoapp
> Update architect version

- CHANGELOG.md
- src/commands/kubeval.yaml
> Change `kubeval` k8s schema to more up-to-date source

- CHANGELOG.md
- src/commands/integration-test-install-tools.yaml
- src/jobs/integration-test.yaml
- src/jobs/run-kat-tests.yaml
- src/jobs/run-tests-with-ats.yaml
See https://gigantic.slack.com/archives/CRZN9GLJW/p1633338999040500
> Use circle's CA certs for curl to avoid letsencrypt bug

- CHANGELOG.md
- docs/job/run-tests-with-ats.md
- src/jobs/run-tests-with-ats.yaml
> Update app-test-suite to 0.2.1

- CHANGELOG.md
- docs/job/run-tests-with-ats.md
- src/jobs/run-tests-with-ats.yaml
Simple version change for ats 0.2.2 - bugfix release.
> upgrade to ats 0.2.2

- CHANGELOG.md
- src/commands/push-to-app-collection.yaml
Towards https://github.com/giantswarm/giantswarm/issues/20705
Requires `architect` v6.0.0
> generate resources for Flux to manage app collections

- CHANGELOG.md
- src/executors/architect.yaml
> Bump architect to v6.0.0

- CHANGELOG.md
- src/commands/push-to-docker.yaml
- src/jobs/push-to-docker.yaml
This PR switches `push-to-docker` job to use [Docker Buildkit](https://docs.docker.com/develop/develop-images/build_enhancements/) and docker 20.10.11
> Use docker buildkit

- CHANGELOG.md
- src/commands/push-to-app-collection.yaml
Towards https://github.com/giantswarm/giantswarm/issues/20900
This is prep for deleting the manifests directory from the collection repos.
> Don't push Argo application CRs to collection

- CHANGELOG.md
- src/commands/push-to-docker.yaml
Towards https://github.com/giantswarm/giantswarm/issues/18546
> Add retries to docker push command

- CHANGELOG.md
- src/jobs/integration-test.yaml
> Update apptestctl to v0.14.1 to fix AppCatalogEntry CRD

- CHANGELOG.md
- src/executors/app-build-suite.yaml
> update abs to v1.1.1

- CHANGELOG.md
- src/executors/app-build-suite.yaml
> update: app-build-suite to 1.1.2

- CHANGELOG.md
- src/commands/helm-conftest.yaml
- src/commands/kubeval.yaml
This PR updates the checks against deprecated api versions in helm charts.
Related: https://gigantic.slack.com/archives/C52L7C6SC/p1649768268294769
> Update deprek8ion and kubeconform to newer kubernetes versions

- docs/job/push-to-app-catalog.md
- src/jobs/push-to-app-catalog.yaml
> Add documentation for OCI app catalogs

- CHANGELOG.md
- src/commands/machine-install-go.yaml
- src/executors/architect.yaml
Towards https://github.com/giantswarm/giantswarm/issues/22048
> Update architect and Go to use Golang 1.18.1

- CHANGELOG.md
- src/jobs/run-tests-with-ats.yaml
- app-test-suite update to 0.2.3
> chg: update app-test-suite to 0.2.3

- CHANGELOG.md
- src/jobs/push-to-app-catalog.yaml
Towards https://github.com/giantswarm/giantswarm/issues/22505
> Push charts to OCI registry by default

- CHANGELOG.md
- src/executors/app-build-suite.yaml
- src/executors/architect.yaml
> Upgrade ABS

- CHANGELOG.md
- docs/job/push-to-app-catalog.md
- src/commands/package-and-push-git-with-abs.yaml
- src/commands/package-and-push-git.yaml
- src/commands/package-and-push-oci-with-abs.yaml
- src/commands/package-and-push-oci.yaml
- src/jobs/push-to-app-catalog.yaml
> Add chart name mismatch parameter when using abs

- CHANGELOG.md
- src/commands/go-build.yaml
- src/commands/go-test.yaml
- src/jobs/go-build.yaml
- src/jobs/go-test.yaml
> Add go test conditional check

- CHANGELOG.md
- docs/job/integration-test.md
- src/jobs/integration-test.yaml
Towards https://github.com/giantswarm/roadmap/issues/2252
> Update apptestctl to v0.15.0

- CHANGELOG.md
- src/executors/architect.yaml
> Bump architect to v6.12.1

- CHANGELOG.md
- docs/job/integration-test.md
- src/jobs/integration-test.yaml
> Update apptestctl to 0.17.0

- CHANGELOG.md
- src/commands/machine-install-go.yaml
- src/executors/architect.yaml
> Update `architect` version to v6.13.0 (includes Go v1.21.3)

- docs/job/push-to-registries.md
> Update docs for push-to-registries

- CHANGELOG.md
- src/commands/image-push-to-registry.yaml
- src/jobs/push-to-registries.yaml
> UX improvements on push-to-registries

- docs/job/push-to-registries.md
> Remove optional image parameter from example

- src/commands/image-push-to-registry.yaml
To be merged into https://github.com/giantswarm/architect-orb/pull/469
> Merge command steps

- CHANGELOG.md
- src/commands/push-to-app-collection.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/29037
> Add version check to `push-to-app-collection` command

- CHANGELOG.md
- src/commands/image-push-to-registry.yaml
> add better retries

- CHANGELOG.md
- docs/job/push-to-docker.md
- docs/job/run-tests-with-ats.md
- src/commands/integration-test-create-cluster.yaml
- src/commands/run-tests-with-ats.yaml
- src/executors/app-build-suite.yaml
- src/executors/architect.yaml
- src/executors/gitleaks.yaml
- src/jobs/push-to-docker.yaml
- src/jobs/run-tests-with-ats.yaml
Towards: https://github.com/giantswarm/roadmap/issues/3083
Tested with:
- https://github.com/giantswarm/flux-app/pull/235
- https://github.com/giantswarm/app-operator/pull/1246
Tested
> Update ABS to `v1.2.2` and use `gsoci.azurecr.io` for images

- CHANGELOG.md
- src/commands/image-push-to-registries.yaml
- src/jobs/push-to-registries.yaml
> fix force-push and some cleanups

- CHANGELOG.md
- src/jobs/run-tests-with-ats.yaml
> Upgrade app-test-suite to v0.6.1

- CHANGELOG.md
- src/executors/architect.yaml
> Bump architect to v6.15.0.

- CHANGELOG.md
- src/executors/architect.yaml
> Bump architect to v6.15.1

- CHANGELOG.md
- src/executors/architect.yaml
- src/jobs/push-to-registries.yaml
Towards: https://github.com/giantswarm/roadmap/issues/3408
Related to: https://github.com/giantswarm/architect/pull/996
> Bump architect to 6.15.0-519d0220a69b4f72f2f594ba802d9628822433a1

- CHANGELOG.md
- src/commands/go-test.yaml
> Set GOGC when running golangci-lint

- CHANGELOG.md
- src/executors/architect.yaml
> Update architect to v6.18

- CHANGELOG.md
- src/jobs/run-tests-with-ats.yaml
> bump ats default version

- CHANGELOG.md
- src/jobs/run-tests-with-ats.yaml
This PR bumps ats to fix ongoing ci issues discussed here https://gigantic.slack.com/archives/C04TGHDEF/p1730233773827769
> bump fixed ats version

- CHANGELOG.md
- docs/job/go-test.md
- src/commands/go-cache-restore.yaml
- src/commands/go-cache-save.yaml
- src/commands/go-test.yaml
- src/executors/architect.yaml
Towards https://github.com/giantswarm/giantswarm/issues/32927
> Remove golangci-lint

- CHANGELOG.md
- src/commands/helm-conftest.yaml
> Print values file name when testing with conftest

- CHANGELOG.md
- src/jobs/run-tests-with-ats.yaml
> update run-test-with-ats job with latest ats version

- CHANGELOG.md
- src/jobs/run-tests-with-ats.yaml
Signed-off-by: Matias Charriere <matias@giantswarm.io>
> Update `run-tests-with-ats` job with latest app-test-suite version.

- CHANGELOG.md
- src/commands/integration-test-install-tools.yaml
- src/executors/app-build-suite.yaml
- src/executors/gitleaks.yaml
- src/jobs/integration-test.yaml
> Update tooling versions and defaults
