.circleci/config.yml, README.md
Towards https://github.com/giantswarm/giantswarm/issues/6025.
This drops "-orb" suffix from the orb name following the pattern in https://github.com/CircleCI-Public/orb-tools-orb.
=> change orb name to giantswarm/architect

CHANGELOG.md, src/commands/package-and-push.yaml
`package-and-push` command currently re-indexes whole app catalog repo, resetting `created` timestamp for all entries when the new package is being added. This is especially problematic for test app catalogs, without semver (only sha) and the timestamp reset it's hard (for Happa) to determine and select latest package.
This PR adjusts the steps of the command to index the new package separately from the rest of the catalog repo content and then merges the two indices.
=> Index new package only on package-and-push

.circleci/config.yml
This PR includes one last change that was omitted in https://github.com/giantswarm/architect-orb/pull/14 as preparation for 0.1.2 release.
=> Prepare 0.1.2 release

CHANGELOG.md, README.md, src/commands/push-to-docker.yaml, src/jobs/push-to-docker.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/6557
Provides a new CircleCI job: `architect/push-to-docker`
Which does the following:
- get the current version we are building
- log into docker registry
- build docker image
- push docker image
This was tested here: https://circleci.com/gh/giantswarm/aws-operator/21548
=> push-to-docker

.circleci/config.yml
Towards: giantswarm/giantswarm#6557
Revert changes after version [0.2.0](https://github.com/giantswarm/architect-orb/pull/20) was released.
=> revert build changes after release

CHANGELOG.md
Small fixed to CHANGELOG.md:
* link to `v0.1.2` version was missing.
* align `Added` header under 0.2.0
=> fixes to changelog

.circleci/config.yml, README.md
After simplifying the release process https://github.com/giantswarm/architect-orb/pull/34 I though it would be cool to also simplify the dev process.
So instead of using `dev:<git-sha>` we can just use `dev:<git-branch>` and remove the need to change the version when we want to test our changes.
This PR replace the `orb-tools/publish-dev` job with `orb-tools/publish` and use `dev:${CIRCLE_BRANCH}` as the orb version.
I tested this and learned that git branch names can be quite funny:
```
$ circleci orb source 'theo/hello@dev:th!s)_is]/a>_va|!d&_branch<_%name+#'
commands:
hello:
steps:
- run: echo hello orb
description: |
Hello orb.
code: https://github.com/TheoBrigitte/hello-orb.
version: 2.1
```
=> Simplify dev versions

CHANGELOG.md, src/commands/push-to-docker.yaml, src/jobs/push-to-docker.yaml
Towards https://github.com/giantswarm/giantswarm/issues/7480
I figured that when architect image is build it's pushed to quay using version from `architect project version` command but the `latest` tag isn't updated. The job is updated to also push `latest` image on (by default) `master` branch.
=> add "tag-latest-branch" parameter to the push-to-docker job

CHANGELOG.md, README.md, src/commands/push-to-docker-legacy.yaml, src/jobs/push-to-docker-legacy.yaml
add new job for pushing the images the old way ( without version, tag is just SHA)
This is for pushing CP components images to china
towards https://github.com/giantswarm/giantswarm/issues/7435
=> add-old-push-docker

CHANGELOG.md, src/commands/push-to-app-collection.yaml, src/jobs/push-to-app-collection.yaml
Towards https://github.com/giantswarm/giantswarm/issues/7648
If `unique` is specified then:
- All other app files will be removed from the collection with `git rm APP-*.yaml`
- This app will be added with `git add APP-unique.yaml`
Note I decided to replace `APP-1.2.3.yaml` with `APP-unique.yaml`. This is because I'd like to have an update instead of replacement in case of unique app. When this is a problem? E.g. with OPA gatekeeper (which we make this feature for) behaviour is undefined (at least to me) when two of them are installed at the same time. So when one app CR is deleting and other creating we don't have a guarantee that there won't be two deployments at the same time.
=> push-to-app-collection: add "unique" parameter

CHANGELOG.md, README.md, src/commands/go-test.yaml
Towards https://github.com/giantswarm/giantswarm/issues/7485
Adds a step to the `go-test` command which runs the command suggested by giantswarm/giantswarm/issues/7485 on *.go files except for the vendor directory.
I think this won't make the job fail but will print offending files in the log. I think some old files are not following the convention defined in fmt. (https://github.com/giantswarm/fmt/blob/master/go/imports.md)
=> Goimports local

CHANGELOG.md, src/commands/push-to-app-collection.yaml
Otherwise the line below fails:
rm .cr_name .version .app_file_name .git_commit_message
=> push-to-app-collection: rename .cr-name to .cr_name to fix cleanup

CHANGELOG.md, src/commands/push-to-app-collection.yaml
This PR fixes an issue with the `unique` parameter in the `push-to-app-collection` job.
When a new app with the unique flag is added to the app-collection, there is no previous app with the same name to be cleaned up and the job fails with the following error:
see https://circleci.com/gh/giantswarm/gatekeeper-control-plane-rules/46
=> fix push-to-app-collection unique parameter

CHANGELOG.md, src/commands/go-test.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8637
We want to invert how the project version is maintained and instead of
generating it from git data and injecting during the build, we want to
maintain it in source files. This will allow managing releases by
merging PRs and that they'll undergo a review process.
=> go-test: stop injecting version into build info

CHANGELOG.md, src/commands/go-lint.yaml, src/executors/go-lint.yaml, src/jobs/go-lint.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8901 https://github.com/giantswarm/giantswarm/issues/7658
Adds `go-lint` job which can run multiple configurable linters.
=> Add golanglint-ci as linter for Go code

CHANGELOG.md, src/commands/gitleaks.yaml, src/executors/gitleaks.yaml, src/jobs/gitleaks.yaml
Adds gitleaks, the first of two language-agnostic secret scanners. This is primarily for entropy-based matching.
Towards https://github.com/giantswarm/giantswarm/issues/8901 and https://github.com/giantswarm/giantswarm/issues/7657
=> Add gitleaks job

src/commands/go-lint.yaml, src/jobs/go-lint.yaml
new-from-rev is suggested so we don't have to re-lint the whole repo on every change, but this could also be removed. The name wouldn't be my first choice, but I want to keep consistency with the upstream tool
Towards https://github.com/giantswarm/giantswarm/issues/8901 and https://github.com/giantswarm/giantswarm/issues/7658
~~- [ ] Update changelog in CHANGELOG.md.~~ - no change
=> Remove params

src/commands/gitleaks.yaml, src/jobs/gitleaks.yaml
I think this would be minimal for us to work with. Keeps the ability to whitelist files and limit the scope to a single commit or changes since the last rev
Toward https://github.com/giantswarm/giantswarm/issues/8901
~~- [ ] Update changelog in CHANGELOG.md.~~ - no change
=> Remove all parameters except config

CHANGELOG.md, src/jobs/push-to-docker-legacy.yaml, src/jobs/push-to-docker.yaml
Related to https://github.com/giantswarm/giantswarm/issues/9240
Removes docker layer caching from remote docker jobs
=> Remove docker layer caching from remote docker setups

.circleci/config.yml, CHANGELOG.md
There was [a bug in the `orb-tools` orb](https://circleci.com/gh/giantswarm/architect-orb/1327) which caused checkouts of repo tags (instead of branches) to fail (in short--checkout requires `git` and `ssh` to be present in image, doesn't find it and uses fallback old version of git which can't checkout repos at tags). The fix https://github.com/CircleCI-Public/orb-tools-orb/pull/46 was released in [8.27.4](https://github.com/CircleCI-Public/orb-tools-orb/compare/v8.27.3...v8.27.4). We're still on 8.3.0 which was released over a year ago. I think this will be sufficient to fix our `architect-orb` build on tag issue which is blocking the [0.8.0 release](https://github.com/giantswarm/architect-orb/pull/88).
=> Update orb-tools to 8.27.6

.circleci/config.yml
Follow-up PR for step 2 in the release checklist of https://github.com/giantswarm/architect-orb/pull/88. I'm using the latest released architect-orb version in the architect-orb CircleCI config.
=> Update to architect-orb v0.8.0

CHANGELOG.md, src/commands/go-lint.yaml, src/commands/go-test-legacy.yaml, src/commands/go-test.yaml, src/executors/architect.yaml, src/executors/go-lint.yaml, src/jobs/go-lint.yaml
Runs golangci-lint as part of the existing go-test and go-test-legacy commands instead of setting up separate environment and using separate executor.
=> Run go-lint as part of go-test command for legacy and modules

CHANGELOG.md
Incorrect merge in last PR - move lint changelog to 0.8.1, will release this version following this PR
=> Release 0.8.1

CHANGELOG.md, src/commands/helm-chart-template.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8635
Tests:
- operator and chart versions don't match https://circleci.com/gh/giantswarm/pawel-test/19
- operator and tag versions don't match https://circleci.com/gh/giantswarm/pawel-test/20
- operator, chart and tag versions match (build fails but the helm-chart-template passes with validation) https://circleci.com/gh/giantswarm/pawel-test/21
=> helm-chart-template: verify chart version in tagged operator builds

CHANGELOG.md, src/commands/helm-lint.yaml
Since we use architect to bump the version of Helm chart, this check isn't
needed. It can in fact lead to false failures as it fails to understand the last
version.
=> Disable Helm version bump

CHANGELOG.md, src/commands/helm-lint.yaml, src/jobs/push-to-app-catalog.yaml
Using `charts` implies that version bump check is disabled, it is also better to
be precise as not all charts in a directory maybe templated correctly. For
example, `push-to-app-catalog` job only takes a single chart and will template
that.
The command can still support multiple charts if need be, but now we can
also specify a single chart.
=> Use `charts` instead of `chart-dirs`

CHANGELOG.md, src/commands/helm-chart-template.yaml
Fixes problem with cleanup command on non-tagged builds.  We should skip in this case.
```
#!/bin/bash -eo pipefail
rm -v .build_*
rm: can't remove '.build_*': No such file or directory
```
e.g. https://circleci.com/gh/giantswarm/chart-operator/9000?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> Fix helm chart template

CHANGELOG.md, docs/integration_test_job.md, src/commands/integration-test-go-test.yaml, src/jobs/integration-test.yaml
We are running tests with a 20m timeout, but since this can be used to run e2e tests, the timeout should be customizable. Our e2e tests for azure-operator take 45 mins in some cases.
=> Make integration test timeout customizable

CHANGELOG.md, docs/push_to_app_catalog_job.md, src/commands/helm-conftest.yaml, src/executors/architect.yaml, src/jobs/push-to-app-catalog.yaml
`conftest` is used to check k8s deprecation policies against k8s manifests in the Helm chart.
Developers can pass their custom policies by specifying the `policy_path` parameter. That folder should contain `rego` policies. 
If no custom policies are passed using the `policy_path` parameter, the default k8s deprecation policies will be used.
=> Run conftest to helm chart

CHANGELOG.md, docs/common.md, docs/integration_test_job.md, docs/push_to_app_catalog_job.md, src/jobs/changelog-lint.yaml, src/jobs/gitleaks.yaml, src/jobs/go-build.yaml, src/jobs/go-test.yaml, src/jobs/integration-test.yaml, src/jobs/push-to-app-catalog.yaml, src/jobs/push-to-app-collection.yaml, src/jobs/push-to-docker.yaml
While switching to architect orb within Go modules work we discovered
that some codebases require more resources for particular jobs. The
problem we hit was aws-operator requiring more memory for building the
binary.
This change adds `resource_class` parameter to all (excluding legacy)
jobs. If not specified in CircleCI the default value is always "medium"
for both machine and docker executors. For some jobs the default is
changed to "small" to save some money.
CircleCI pricing table: https://circleci.com/pricing/#compute-options-table
=> jobs: add resource_class parameters to all jobs

CHANGELOG.md, src/commands/go-build.yaml, src/commands/go-test.yaml
=> Make ldflags compatible with go modules with versions >= 2

CHANGELOG.md, README.md, src/commands/push-to-app-collection.yaml
Towards https://github.com/giantswarm/giantswarm/issues/10423.
Retry the `git push` up to 4 times with some wait times in between in
case it fails, in order to cope with transient errors better.
=> commands/push-to-app-collection: retry the push

CHANGELOG.md, src/commands/package-and-push.yaml, src/commands/push-to-app-collection.yaml
I just copied @mig4 work from https://github.com/giantswarm/architect-orb/pull/140 and adjusted to catalog.
=> push-to-app-catalog: retry git push

CHANGELOG.md, docs/run_kat_tests.md, src/commands/helm-lint.yaml, src/commands/kat-tests-run.yaml, src/jobs/push-to-app-catalog.yaml, src/jobs/run-kat-tests.yaml
This is to support the use of additional Helm chart repositories.
Config file is needed for this option according to the docs
https://github.com/helm/chart-testing/tree/v2.4.1#using-private-chart-repositories
Additional repos are needed to satisfy Chart dependencies when testing. Maybe in
the future we can copy all dependencies to our own catalogs, then we won't need
to rely on external deps and we can just add our catalogs. But until that is
in place, we need a way to specify repos.
=> Support Chart testing config file

CHANGELOG.md, src/commands/integration-test-install-tools.yaml
If we don't install this exact version our Helm client fails.
=> Our helm client requires Helm v2.16.1

CHANGELOG.md, src/commands/integration-test-install-tools.yaml
Installing `kind` from go modules affects `go.mod` in the project. 
We could rather do it from the different directory but I think installing binary files is much cleaner.
=> Install kind by binary

CHANGELOG.md, src/commands/go-test-legacy.yaml, src/commands/go-test.yaml, src/executors/architect.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8901
Adds `nancy` to scan for vulnerable Go dependencies
=> Add nancy - scans for vulnerabilities in dependencies

CHANGELOG.md, src/commands/machine-install-go.yaml
Current architect-orb v0.12.0 uses architect v3.0.0 https://github.com/giantswarm/architect-orb/blob/master/CHANGELOG.md#0120---2020-09-28
Architect v3.0.0 was updated to go v1.15.2 https://github.com/giantswarm/architect/blob/master/CHANGELOG.md#300---2020-09-24
This PR aligns go version used in architect-orb's machine-install-go command (used in integration-test job) to v1.15.2.
=> Update Go version used in integration test to 1.15.2

src/commands/package-and-push.yaml
This PR adds some step names to the `package-and-push` action/workflow/whatever the term is.
The goal here is to make the CI steps easier to interpret for developers who didn't author architect-orb.
=> Make 'package-and-push' more readable

CHANGELOG.md, src/jobs/run-kat-tests.yaml
@piontec You were right in #191. It seems the job also needs the defaults
=> set default verions for kind, helm and kubectl in run-kat-tests job

CHANGELOG.md, src/commands/integration-test-create-cluster.yaml, src/commands/integration-test-go-test.yaml, src/commands/integration-test-install-tools.yaml, src/jobs/integration-test.yaml
Towards https://github.com/giantswarm/giantswarm/issues/13206
The job hasn't been updated in a while. This gets it sorted and is prep for adding support for using `apptestctl bootstrap`.
=> Update versions in integration test job and remove obsolete code

CHANGELOG.md, docs/job/integration-test.md, src/commands/integration-test-install-app-platform.yaml, src/jobs/integration-test.yaml
Towards giantswarm/giantswarm#13206
Tested in https://github.com/giantswarm/metrics-server-app/pull/36/
=> Add support for apptestctl bootstrap to integration-test job

.circleci/config.yml, CHANGELOG.md, docs/job/push-to-docker.md, src/commands/push-to-docker.yaml, src/jobs/push-to-docker.yaml
This PR adds parameters `build-context`, `dockerfile` and `tag-suffix` to the `push-to-docker` jobs.
I want to push a container image built from a custom Dockerfile to the same container repo with a custom tag suffix.
=> Add some parameters to push-to-docker

CHANGELOG.md, src/commands/integration-test-install-app-platform.yaml, src/jobs/integration-test.yaml
New apptestctl release adds better kubeconfig support and we now wait for app platform components to start which makes the tests more reliable. 
https://github.com/giantswarm/apptestctl/blob/master/CHANGELOG.md#050---2020-11-27
=> Use apptestctl v0.5.0 in integration-test job.

CHANGELOG.md, docs/job/push-to-app-catalog.md, src/commands/package-and-push-with-abs.yaml, src/commands/package-and-push.yaml
Towards giantswarm/giantswarm#9815
This PR loosens the chart name validation to allow both `repository-name` and `repository-name-app`.
=> Relax chart parameter validation in push-to-app-catalog job

.circleci/config.yml, CHANGELOG.md, src/commands/kat-tests-install-tools.yaml, src/jobs/run-kat-tests.yaml
This PR bumps the default helm version used by `run-kat-tests` job to 2.17.0.
This should resolve errors recently surfaced (`Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden`)
=> Bump helm version in run-kat-tests job to 2.17.0

.circleci/config.yml, CHANGELOG.md, docs/README.md, docs/job/run-tests-with-abs.md, src/commands/run-tests-with-abs.yaml, src/executors/app-build-suite.yaml, src/jobs/run-tests-with-abs.yaml
This PR bumps the app-build-suite version in the app-build-suite executor
It also adds an experimental `run-tests-with-abs` job.
=> Bump app build suite version

.circleci/config.yml, CHANGELOG.md, src/commands/package-and-push-with-abs.yaml, src/commands/package-and-push.yaml
Towards https://github.com/giantswarm/giantswarm/issues/15898
This PR updates the app-catalog base domain to giantswarm.github.io because the redirect from .com to .io will be shut off in 2021-04-15
=> Update catalog index base hosts to giantswarm.github.io

.circleci/config.yml, CHANGELOG.md, docs/job/push-to-app-catalog.md, src/commands/package-and-push.yaml, src/jobs/push-to-app-catalog.yaml
This PR adds parameter `explicit_allow_chart_name_mismatch` to allow disabling chart name check in `push-to-app-catalog`
=> Allow chart name mismatch

CHANGELOG.md, docs/job/run-tests-with-abs.md, src/executors/app-build-suite.yaml, src/jobs/run-tests-with-abs.yaml
Upgrade app-build-suite executor to use 0.2.1
=> Upgrade app-build-suite executor to use 0.2.1

.circleci/config.yml, CHANGELOG.md, src/commands/go-test.yaml, src/commands/machine-install-go.yaml, src/executors/architect.yaml
Together with https://github.com/giantswarm/architect/pull/592,
this upgrades the used go version to 1.16.2 and architect to 3.4.0
From architect-changelog:
```
- Update `go` version to `v1.16.2`.
- Update `helm` version to `v3.5.3`.
- Update `alpine` version to `3.13`.
- Update `conftest` version to `v0.21.0`.
- Update `golangci-lint` version to `v1.38.0`.
- Update `nancy` version to `v1.0.17`.
- Update `helm-chart-testing` to `v3.3.1`.
```
=> Update go to 1.16.2 and architect to 3.4.0

CHANGELOG.md, docs/job/push-to-app-catalog.md, src/commands/package-and-push.yaml, src/jobs/push-to-app-catalog.yaml
This is not ideal, but is going to be the most developer-friendly for the short term.
When building `clusterpolicies`, we need to package `ClusterPolicy` CRs, which use a very specific notation used by kyverno. Helm [does not like this notation](https://app.circleci.com/pipelines/github/giantswarm/clusterpolicies/20/workflows/7e4381ab-0363-451e-8261-a513710e1dc2/jobs/29). Additionally, kustomize mangles the policies by rearranging keys and changing quotations, which are also meaningful to the kyverno policy parser.
The long-term fix to this might be
- ask kyverno to add schema and linting config for policies
- package and [deploy policies](https://github.com/giantswarm/cert-manager-app/blob/master/helm/cert-manager-app/templates/crd-install/crd-job.yaml) from [inside …
=> Allow skipping ct lint

.circleci/config.yml
Bumping the orb version after the release, per instructions https://github.com/giantswarm/architect-orb/pull/256
=> Bump architect-orb to 2.5.0

.circleci/config.yml, CHANGELOG.md, src/commands/prepare-catalogbot-git-ssh.yaml
This PR adds a command for setting up the catalogbot public ssh key from its private key
This is required because it seems circle CI changed something how they set up the read-only deploy ssh keys.
Here is what I think happens:
- CircleCI starts the container
- Uses the deploy key to clone the code, the public and private ssh key ends up in the ssh-agent
- We overwrite only the private key file. The public key file is the old one
- We try to push into the catalog repo, but the key from the agent is used
After this PR gets merged and released, `ssh-keygen` is used to refresh the public ssh key from the already overwritten private key.
I tested this for both `architect` and `app-build-suite` based builds of `push-to-app-catalog`.
Related Slack thread: …
=> re-generate public ssh key after setting up catalog bot private key

CHANGELOG.md, src/commands/push-to-app-collection.yaml, src/executors/architect.yaml
With Argo CD syncing App CRs from collection, we need to drop status field completely otherwise Argo tries to sync it with empty values we have inside the Github repo
=> Remove .status field from App CR

CHANGELOG.md, src/commands/integration-test-install-tools.yaml, src/jobs/integration-test.yaml
=> Update Kubernetes to 1.21.1 and KIND to 0.11.0 in integration-test job

CHANGELOG.md, src/executors/architect.yaml
Towards https://github.com/giantswarm/giantswarm/issues/17297
- Tested in https://github.com/giantswarm/management-cluster-admission/pull/52
- Test 1: with with annotation:
- [CI run](https://app.circleci.com/pipelines/github/giantswarm/management-cluster-admission/144/workflows/1d15f486-bba0-491a-b716-76199370cd6b/jobs/645)
- [Collection commit](https://github.com/giantswarm/pawel-collection/commit/e9ca1623dcabebf068ec0795b7ee27d46d81af22)
- Test 2: no config annotation in Chart.yaml:
- [CI run](https://app.circleci.com/pipelines/github/giantswarm/management-cluster-admission/145/workflows/695194e0-369f-40d5-a578-cec1b637e502/jobs/646)
- [Collection commit](https://github.com/giantswarm/pawel-collection/commit/cb7072cbc4ed64e72cdd76e27002e70bfe0656f6) note sync policy changes
- Test 3: …
=> Update architect to 3.6.0

.circleci/config.yml, CHANGELOG.md, docs/job/run-tests-with-abs.md, src/executors/app-build-suite.yaml, src/jobs/run-tests-with-abs.yaml
Bump app-build-suite to [v0.2.3](https://github.com/giantswarm/app-build-suite/releases/tag/v0.2.3) ([Changelog](https://github.com/giantswarm/app-build-suite/blob/master/CHANGELOG.md#023---2021-05-24))
=> Bump app build suite to v0.2.3

CHANGELOG.md, docs/job/push-to-app-catalog.md, src/commands/package-and-push.yaml, src/jobs/push-to-app-catalog.yaml
Fixes https://github.com/giantswarm/giantswarm/issues/17650
This option was added to support deploying kyverno policies with release-operator. This is no longer needed. AFAICT this was only ever used by kyverno-policies, and it has been removed https://github.com/giantswarm/kyverno-policies/pull/33
=> Remove option to skip helm chart linting

CHANGELOG.md, src/jobs/integration-test.yaml
Toward giantswarm/roadmap#219
To create `Catalog` CRD from the integration test, we need to update apptestctl to 0.9.0.
=> Update apptestctl to 0.9.0

.circleci/config.yml, CHANGELOG.md, docs/job/push-to-app-catalog.md, src/commands/helm-conftest.yaml, src/commands/package-and-push-with-abs.yaml, src/jobs/push-to-app-catalog.yaml
This PR updates the deprek8ion rules used in the `conftest` step executed by `push-to-app-catalog` job.
This will fail for outdated manifests deprecated in kubernetes 1.16 to 1.20
=> Update deprek8ion rules to check for deprecated manifests

.circleci/config.yml, CHANGELOG.md, src/commands/machine-install-go.yaml, src/executors/architect.yaml
This PR updates the used architect version to 5.2.0 to make use of Go 1.17.1 in CI builds.
I'll merge this on monday. Afterwards I'll update the github automation.
=> Bump architect (and go)

CHANGELOG.md, src/commands/helm-diff.yaml, src/commands/kubeval.yaml, src/executors/architect.yaml, src/jobs/push-to-app-catalog.yaml
Towards: giantswarm/giantswarm#18975
The goal here is to ensure we do not have conflicting/overlapping files in the helm chart which would overwrite at deploy time, see https://github.com/giantswarm/giantswarm/issues/18975#issuecomment-928042528.
=> add `kubeval` validation to `push-to-app-catalog` job.

CHANGELOG.md, src/commands/go-build.yaml, src/jobs/go-build.yaml
This PR adds support for specifying custom tags for the `tags` flag of `go build`.
=> Add tags parameter to go-build

CHANGELOG.md, docs/job/integration-test.md, src/commands/integration-test-install-app-platform.yaml, src/commands/integration-test-install-tools.yaml, src/jobs/integration-test.yaml
Needed so we can use apptestctl to install CRDs in app-operator and chart-operator tests.
Otherwise we hit GitHub rate limits.
=> Always install apptestctl binary in integration-test job

CHANGELOG.md, src/commands/machine-install-go.yaml, src/executors/architect.yaml
This PR updates dependencies to use Go 1.17.7
=> Update architect and Go to use Golang 1.17.7

CHANGELOG.md, src/commands/machine-install-go.yaml, src/executors/architect.yaml
his PR updates dependencies to use Go 1.17.8
=> Update go 1.17.8 and architect 6.3.0

CHANGELOG.md, src/commands/package-and-push-with-abs.yaml, src/commands/package-and-push.yaml
Towards https://github.com/giantswarm/giantswarm/issues/21059
Fixes problem discovered in https://github.com/giantswarm/default-apps-openstack/pull/30 - https://app.circleci.com/pipelines/github/giantswarm/default-apps-openstack/158/workflows/adc5b3c2-0a23-4712-b19b-26b02548715a/jobs/158. `cluster-catalog` uses `main` as the default branch instead of `master`. I don't see any reason to specify `-b` as git will automatically check out the default branch. Tested locally.
=> Remove specific branch checkout

CHANGELOG.md, src/commands/push-to-docker.yaml
Currently the `docker build` output (introduced some versions ago) does not work well for CI, as it's meant for interactive TTYs. This PR switches on the plain progress logging.
=> Set 'docker build' flag for plain progress logging

CHANGELOG.md, src/commands/package-and-push-git-with-abs.yaml, src/commands/package-and-push-git.yaml, src/commands/package-and-push-oci-with-abs.yaml, src/commands/package-and-push-oci.yaml, src/jobs/push-to-app-catalog.yaml
Towards https://github.com/giantswarm/roadmap/issues/391
=> Add a command to push to OCI registries

CHANGELOG.md, src/commands/go-test.yaml
This PR allow to use a second `.nancy-ignore.local` file to be able to ignore some CVEs without to go through the `github` repository sync.
Syncing `.nancy-ignore` accross repositories with `github` is good for global CVEs, but we also need a mechanism with an easy  per repo ignore solution. cc/ @hervenicol 
The file given in `--exclude-vulnerability-file` is not required to exist, it just skip if not found. This works : 
```
$ CGO_ENABLED=0 go list -json -m all | nancy sleuth --skip-update-check --quiet --exclude-vulnerability-file ./.nancy-ignore --exclude-vulnerability-file ./.non-existent-file
```
=> add a second .nancy-ignore.local file

CHANGELOG.md, src/commands/go-test.yaml
Revert `.nancy-ignore.local` file, which does not work in combination with the current `.nancy-ignore` file, as `nancy` only accept one `--exclude-vulnerability-file` and take the latest.
=> revert non-working .nancy-ignore.local

CHANGELOG.md, src/commands/go-test.yaml, src/executors/architect.yaml
If the file does not exist then it will be ignored by nancy.
=> Use extra ignore file for nancy checks

CHANGELOG.md, src/commands/machine-install-go.yaml, src/executors/architect.yaml
- Update `architect` version to [`v6.7.0`](https://github.com/giantswarm/architect/releases/tag/v6.7.0).
- Update Go version used in `machine-install` command to 1.19.1.
=> Update golang to v1.19.1

CHANGELOG.md, src/commands/go-test.yaml
On (so far) rare occasions, the OSS Index back end for `nancy` is unreachable. When this happens, we can't scan, and there's no way to skip or ignore a step in architect.
This PR attempts to let the build continue if the back end is down, based on the limited data available from the last time it happened. 
Can be seen in action [here (no CVE case)](https://app.circleci.com/pipelines/github/giantswarm/starboard-exporter/672/workflows/5a8801ec-5b86-421c-95c1-e61781f14b58/jobs/3472) and [here (CVE found case)](https://app.circleci.com/pipelines/github/giantswarm/starboard-exporter/674/workflows/6139e099-a61a-41c4-a1f9-73559fb292ff/jobs/3480). I wasn't able to force a 500 error in CI to test the grep, but did my best locally.
Related: https://github.com/giantswarm/giantswarm/issues/24153
=> Ignore nancy failure if OSS index is down

CHANGELOG.md, src/commands/go-test.yaml
Fix `go test` command error ignore logic for external `nancy` service failures.
Resolves giantswarm/giantswarm#25912
=> Command go test: Fix Nancy External Service Error Ignore

CHANGELOG.md, src/commands/machine-install-go.yaml, src/executors/architect.yaml
This PR updates architect and go for 1.19.6
=> Upgrade architect (6.10.0) and go (1.19.6)

CHANGELOG.md, src/commands/go-build.yaml, src/commands/go-test.yaml, src/jobs/go-build.yaml, src/jobs/go-test.yaml
This allows a Makefile target to be executed when specified and is helpful for generating code before any linters run.
Specifically, I've tested this change with https://github.com/giantswarm/capa-iam-operator/pull/161, in which I require code generation to run before linters.
=> Add `pre_test_target` parameter to `go-build` and `go-test` jobs

CHANGELOG.md, src/executors/architect.yaml
Blocked by https://github.com/giantswarm/architect/pull/811 followed by a new minor release.
=> Bump Architect image to latest

CHANGELOG.md, src/jobs/run-tests-with-ats.yaml
This PR bumps the `app-test-suite` version for the `run-tests-with-ats` CircleCI job to v0.4.1 by default.
=> Update app-test-suite to v0.4.1 in run-tests-with-ats  CircleCI job

CHANGELOG.md
There was a duplicate "[Unreleased]" entry
=> Fix changelog to unblock release automation

CHANGELOG.md, docs/job/integration-test.md, src/jobs/integration-test.yaml
Bumps apptestctl to v0.18.0 to install VPA and PolicyException CRDs
=> Bump apptestctl to v0.18.0

CHANGELOG.md, src/commands/go-test.yaml
This PR changes the `go list` command that lists Go dependencies.
Previously we were using `go list -m all`, which returned more Go modules than were used in the current project. This resulted in nancy reporting vulnerabilities of modules that weren't even used in the project.
The nancy docs recommends to use `go list -deps ./...`, which is what we are changing towards.
=> Prevent false positives from nancy

CHANGELOG.md, src/commands/machine-install-go.yaml
I had downloaded the archive with `curl -O`, missing `-L` to follow the redirect to the actual tarball download. So I had hashed an HTML redirect page 🙈.
=> Fix Go checksum for `machine-install-go` command

docs/README.md, docs/job/push-to-docker.md
Towards https://github.com/giantswarm/roadmap/issues/2882
=> Deprecate push-to-docker, update docs job list to include push-to-registries

CHANGELOG.md, docs/job/push-to-registries.md, src/@orb.yml, src/commands/image-push-to-registry-v2.yaml, src/jobs/push-to-registries.yaml
Towards https://github.com/giantswarm/roadmap/issues/2882 , https://github.com/giantswarm/roadmap/issues/2915
This PR allows to configure whether dev builds should be pushed, per registry.
Also the `image` parameter is made optiona and defaults to the format `orga_name/repo_name` now.
=> Make pushing dev builds configurable

CHANGELOG.md, src/commands/image-build-with-docker.yaml
Made the `image-build-with-docker` command work in a situation where the `docker build` command would output the image SHA more than once.
=> Fix docker SHA detection in image-build-with-docker command

CHANGELOG.md, src/commands/go-test.yaml
By default, `golangci-lint` reports only 3 items of a particular type of error.
This can cause extra round-trips if developers only rely on the CI check. By adding `--max-same-issues 0` to the execution, all occurrences of the issues found are printed.
=> Let golangci-lint report more than 3 items of the same type of complaint

CHANGELOG.md, src/commands/image-login-to-registries.yaml, src/commands/image-push-to-registries.yaml, src/jobs/push-to-registries.yaml
- `push-to-registries` job changes:
- remove deprecated `push-to-*` config options
- login to registries before an image is built, so it's possible to use private base images
=> `push-to-registries` fix order and params cleanup

.circleci/config.yml
This adds the `pub_type: production` parameter to the `publish-tag` step.
See https://circleci.com/developer/orbs/orb/circleci/orb-tools#jobs-publish
=> Ensure publishing a prod version on tag

CHANGELOG.md, src/executors/machine.yaml, src/jobs/integration-test.yaml, src/jobs/run-kat-tests.yaml, src/jobs/run-tests-with-ats.yaml
Signed-off-by: Matias Charriere <matias@giantswarm.io>
This PR:
- Moves `machine.image` to the executor `machine`
- Updates from `ubuntu-2004:202010-01` to `default` following the [instructions from CircleCI](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177)
Unfortunately CircleCI is deprecating version pinning on machine images, and instead adopting a floating tag.
=> Move machine image to machine executor

CHANGELOG.md, src/commands/image-prepare-tag.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/30055
The command substitution hides the return code from the `architect project version` call. CircleCI runs the script with `-eo pipefail` ([reference](https://circleci.com/docs/configuration-reference/#default-shell-options) + [example](https://app.circleci.com/pipelines/github/giantswarm/giantswarm/11900/workflows/50a61db0-579f-49df-a8b5-0502b8d3d35d/jobs/15865?invite=true#step-104-0_69)).
=> Make prepare image tag command fail when architect call fails

CHANGELOG.md, src/jobs/run-tests-with-ats.yaml
Waiting on: https://github.com/giantswarm/app-test-suite/pull/308
=> Update app-test-suite to v0.6.0

CHANGELOG.md, src/executors/architect.yaml
Updates architect to v6.17.0, which includes golangci-lint v1.60.1 that is compiled with/supports go 1.23
(see https://github.com/giantswarm/architect/pull/1005, with earlier versions linting jobs are getting killed because of RAM usage, e.g. https://app.circleci.com/pipelines/github/giantswarm/cert-exporter/1317/workflows/a9eda581-f647-4237-9c7f-15cc7c6aa7c8/jobs/6013/steps).
=> Bump architect to v6.17.0, necessary to support go 1.23.

CHANGELOG.md, src/commands/go-cache-restore.yaml, src/commands/go-cache-save.yaml, src/commands/go-test.yaml
In this PR I'm mainly removing the separate execution of `go vet`, as it's redundant with the checks executed by `golangci-lint`.
Additional changes:
- Set `--max-issues-per-linter` to 0 (unlimited) in golangci-lint execution
- Using the `environment` key to set environment variables in a more idiomatic way
- Run `go test` before golangci-lint (see below)
- Adding a persistent cache for `golangci-lint`. We'll have to evaluate in practice whether this really speeds up anything.
---
During testing I noticed that `golangci-lint` can take a relatively long time to end up finding a compilation problem, like a breaking API change in a major dependency upgrade.
To catch problems like this faster, I moved the `go test` step to happen before the `golangci-lint` step. This means that compilation …
=> `go-test`: remove go vet, tweak golangci-lint, change order

CHANGELOG.md, src/commands/push-to-app-collection.yaml
It is currently impossible to push a new app in a collection because there is no base file to compare version with like so https://app.circleci.com/pipelines/github/giantswarm/alloy-app/192/workflows/500bf071-f394-499d-a823-565718fd6262/jobs/237
=> allow-app-creation-in-collection

CHANGELOG.md, src/commands/helm-conftest.yaml, src/jobs/push-to-app-catalog.yaml
Run `conftest` after `app-build-suite` to prevent conftest being sad about missing subchart depndencies
=> Run `conftest` after `app-build-suite` in `push-to-app-catalog` job

src/commands/run-kyverno.yaml
This pull request includes an important change to the `src/commands/run-kyverno.yaml` file to improve the Helm chart installation process.
It adds  a step to install chart dependencies using `helm dependency update` before templating the Helm chart.
=> Run helm dependency update before helm tempalte in kyverno test

CHANGELOG.md, src/commands/go-build.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/33157
This PR removes the check for version command in the `go-build` job.
This check was in place to ensure a version command was present in the built binary, this applied to binaries built with operatorkit. This is no longer required and the check silently fails which make it useless.
=> Remove version command check

src/executors/architect.yaml
Uses https://github.com/giantswarm/architect/pull/1123
=> Use dev version of architect to downgrade to golangci-lint v1.64.8

CHANGELOG.md, docs/job/go-build.md, docs/job/image-build-and-push-multiarch.md, docs/job/push-to-registries.md, src/commands/go-build.yaml, src/commands/image-build-and-push-multiarch.yaml, src/commands/image-push-to-registries.yaml, src/jobs/go-build.yaml, src/jobs/push-to-registries-multiarch.yaml
This pull request introduces multi-architecture support for Go builds and container image workflows, enhancing flexibility and modernizing the pipeline. Key changes include the addition of new parameters and jobs to handle multi-architecture builds, deprecation of older parameters, and updates to documentation for clarity.
These changes ensure backward compatibility while enabling modern multi-architecture workflows for both Go builds and container image publishing.
=> add multiarch support
